# Generated by Django 2.1.5 on 2020-06-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catrgories',
            new_name='categories',
        ),
    ]
