# Generated by Django 2.1.5 on 2020-06-17 10:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200617_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
