# Generated by Django 2.1.5 on 2020-06-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='servce_subtitle',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_brief',
        ),
    ]
